[build]
  # Indique à Netlify où se trouvent les fonctions.
  # Netlify ira chercher les fonctions dans ce dossier.
  functions = "netlify/functions"
  # Indique à Netlify de publier le contenu de la racine du dépôt (votre index.html).
  publish = "."

[functions]
  # Assure que Netlify utilise le bundler Node.js (zisi) qui gère l'installation
  # des dépendances listées dans le package.json racine.
  node_bundler = "zisi"
